name: Auto Assign Reviewers and Assignee

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Auto assign reviewers and assignee
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.actor.toLowerCase();
            const pr = context.payload.pull_request;

            const members = [
              'leehb-1007',
              'limsr12',
              'jangdongho',
              'devjunz',
              'whateveriiwant'
            ];

            // 전원 리뷰(작성자 제외)
            const reviewers = members.filter(m => m !== prAuthor);

            console.log(`PR Author: ${prAuthor}`);
            console.log(`Assigned reviewers: ${reviewers.join(', ')}`);

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              reviewers
            });

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: [prAuthor]
            });
