import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/widgets/Header';
import Footer from '@/widgets/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className="flex min-h-screen flex-col font-sans antialiased">
        <Header />
        <main className="bg-neutral-surface-default flex w-full flex-1 flex-col items-center px-4 py-32">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
