import type { Metadata } from 'next';
<<<<<<< HEAD
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/widgets/Header';
import Footer from '@/widgets/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
=======
import './globals.css';
import Header from '@/widgets/Header';
import Footer from '@/widgets/Footer';
import localFont from 'next/font/local';
>>>>>>> b0b0a9b5acc5e6d930c5aa256016eb1aee0deb4e

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
=======
    <html lang="en" className={`${pretendard.variable}`}>
      <body className="font-sans antialiased flex flex-col min-h-screen">
>>>>>>> b0b0a9b5acc5e6d930c5aa256016eb1aee0deb4e
        <Header />
        <main className="flex flex-col flex-1 items-center bg-[#F0F4FA] px-4 pt-24 w-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
