-- AlterTable
ALTER TABLE `answers` MODIFY `state` ENUM('PUBLISHED', 'PRIVATE', 'DELETED') NOT NULL DEFAULT 'PUBLISHED';

-- AlterTable
ALTER TABLE `projects` MODIFY `state` ENUM('PUBLISHED', 'PRIVATE', 'DELETED') NOT NULL DEFAULT 'PUBLISHED';

-- AlterTable
ALTER TABLE `questions` MODIFY `state` ENUM('PUBLISHED', 'PRIVATE', 'DELETED') NOT NULL DEFAULT 'PUBLISHED';

-- AlterTable
ALTER TABLE `stories` MODIFY `state` ENUM('PUBLISHED', 'PRIVATE', 'DELETED') NOT NULL DEFAULT 'PUBLISHED';
